version: "3.7"

services:
  studyship-front:
    container_name: devti-compose
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    tty: true
