name: Slack
on: [pull_request]

jobs:
  create-pr:
    runs-on: ubuntu-latest
    name: Slack Notification
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Fire Notification
        uses: Lubycon/github-reviewer-slack-noti-action@v1.1.2
        with:
          github-token: ${{ secrets.LUBYCON_GITHUB_TOKEN }}
          channel-id: C01SSJ6HGTH
